### ISSUE TITLE
Failed to install 'felixfbecker.php-pack'.

### ISSUE THREAD

**Issue by websafe** [felixfbecker/vscode-php-pack#9]
I'm trying to install on Windows 10 and I'm getting `Failed to install 'felixfbecker.php-pack'.`

**Comment by websafe** [comment]
Tried to install from VSIX:

```
04/10/2018 10:18:18 - Microsoft VSIX Installer
04/10/2018 10:18:18 - -------------------------------------------
04/10/2018 10:18:18 - Initializing Install...
04/10/2018 10:18:18 - Extension Details...
04/10/2018 10:18:18 - 	Identifier      : php-pack
04/10/2018 10:18:18 - 	Name            : PHP Extension Pack
04/10/2018 10:18:18 - 	Author          : felixfbecker
04/10/2018 10:18:18 - 	Version         : 1.0.2
04/10/2018 10:18:18 - 	Description     : Everything you need for PHP development
04/10/2018 10:18:18 - 	Locale          : en-US
04/10/2018 10:18:18 - 	MoreInfoURL     : 
04/10/2018 10:18:18 - 	InstalledByMSI  : False
04/10/2018 10:18:18 - 	SupportedFrameworkVersionRange : [0.0,2147483647.2147483647]
04/10/2018 10:18:18 - 
04/10/2018 10:18:18 - 	Supported Products : 
04/10/2018 10:18:18 - 		Microsoft.VisualStudio.Code
04/10/2018 10:18:18 - 			Version : 
04/10/2018 10:18:18 - 
04/10/2018 10:18:18 - 	References      : 
04/10/2018 10:18:18 - 
04/10/2018 10:18:18 - Searching for applicable products...
04/10/2018 10:18:18 - Found installed product - Global Location
04/10/2018 10:18:18 - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.App.InitializeInstall(Boolean isRepairSupported)
   at VSIXInstaller.App.InitializeInstall()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
```

**Comment by websafe** [comment]
After restarting vscode everything went fine. Case closed 8-)
